/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AirdropInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claim"
      | "claimed"
      | "closeClaim"
      | "closeRegistration"
      | "getConfigId"
      | "getScope"
      | "isClaimOpen"
      | "isRegistered"
      | "isRegistrationOpen"
      | "merkleRoot"
      | "onVerificationSuccess"
      | "openClaim"
      | "openRegistration"
      | "owner"
      | "renounceOwnership"
      | "scope"
      | "setConfigId"
      | "setMerkleRoot"
      | "token"
      | "transferOwnership"
      | "verificationConfigId"
      | "verifySelfProof"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ClaimClose"
      | "ClaimOpen"
      | "Claimed"
      | "MerkleRootUpdated"
      | "OwnershipTransferred"
      | "RegistrationClose"
      | "RegistrationOpen"
      | "UserIdentifierRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claim",
    values: [BigNumberish, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "closeClaim",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "closeRegistration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getConfigId",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getScope", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isClaimOpen",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistrationOpen",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "merkleRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onVerificationSuccess",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "openClaim", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "openRegistration",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "scope", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setConfigId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMerkleRoot",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verificationConfigId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifySelfProof",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "closeClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "closeRegistration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConfigId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getScope", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isClaimOpen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistrationOpen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "merkleRoot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onVerificationSuccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "openClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "openRegistration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "scope", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setConfigId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verificationConfigId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifySelfProof",
    data: BytesLike
  ): Result;
}

export namespace ClaimCloseEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimOpenEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimedEvent {
  export type InputTuple = [
    index: BigNumberish,
    account: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [index: bigint, account: string, amount: bigint];
  export interface OutputObject {
    index: bigint;
    account: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MerkleRootUpdatedEvent {
  export type InputTuple = [newMerkleRoot: BytesLike];
  export type OutputTuple = [newMerkleRoot: string];
  export interface OutputObject {
    newMerkleRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegistrationCloseEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegistrationOpenEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserIdentifierRegisteredEvent {
  export type InputTuple = [
    registeredUserIdentifier: BigNumberish,
    nullifier: BigNumberish
  ];
  export type OutputTuple = [
    registeredUserIdentifier: bigint,
    nullifier: bigint
  ];
  export interface OutputObject {
    registeredUserIdentifier: bigint;
    nullifier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Airdrop extends BaseContract {
  connect(runner?: ContractRunner | null): Airdrop;
  waitForDeployment(): Promise<this>;

  interface: AirdropInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claim: TypedContractMethod<
    [index: BigNumberish, amount: BigNumberish, merkleProof: BytesLike[]],
    [void],
    "nonpayable"
  >;

  claimed: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  closeClaim: TypedContractMethod<[], [void], "nonpayable">;

  closeRegistration: TypedContractMethod<[], [void], "nonpayable">;

  getConfigId: TypedContractMethod<
    [
      destinationChainId: BytesLike,
      userIdentifier: BytesLike,
      userDefinedData: BytesLike
    ],
    [string],
    "view"
  >;

  getScope: TypedContractMethod<[], [bigint], "view">;

  isClaimOpen: TypedContractMethod<[], [boolean], "view">;

  isRegistered: TypedContractMethod<
    [registeredAddress: AddressLike],
    [boolean],
    "view"
  >;

  isRegistrationOpen: TypedContractMethod<[], [boolean], "view">;

  merkleRoot: TypedContractMethod<[], [string], "view">;

  onVerificationSuccess: TypedContractMethod<
    [output: BytesLike, userData: BytesLike],
    [void],
    "nonpayable"
  >;

  openClaim: TypedContractMethod<[], [void], "nonpayable">;

  openRegistration: TypedContractMethod<[], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  scope: TypedContractMethod<[], [bigint], "view">;

  setConfigId: TypedContractMethod<[configId: BytesLike], [void], "nonpayable">;

  setMerkleRoot: TypedContractMethod<
    [newMerkleRoot: BytesLike],
    [void],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verificationConfigId: TypedContractMethod<[], [string], "view">;

  verifySelfProof: TypedContractMethod<
    [proofPayload: BytesLike, userContextData: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<
    [index: BigNumberish, amount: BigNumberish, merkleProof: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimed"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "closeClaim"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "closeRegistration"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getConfigId"
  ): TypedContractMethod<
    [
      destinationChainId: BytesLike,
      userIdentifier: BytesLike,
      userDefinedData: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getScope"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isClaimOpen"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[registeredAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRegistrationOpen"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "merkleRoot"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "onVerificationSuccess"
  ): TypedContractMethod<
    [output: BytesLike, userData: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "openClaim"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "openRegistration"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "scope"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setConfigId"
  ): TypedContractMethod<[configId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMerkleRoot"
  ): TypedContractMethod<[newMerkleRoot: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verificationConfigId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifySelfProof"
  ): TypedContractMethod<
    [proofPayload: BytesLike, userContextData: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ClaimClose"
  ): TypedContractEvent<
    ClaimCloseEvent.InputTuple,
    ClaimCloseEvent.OutputTuple,
    ClaimCloseEvent.OutputObject
  >;
  getEvent(
    key: "ClaimOpen"
  ): TypedContractEvent<
    ClaimOpenEvent.InputTuple,
    ClaimOpenEvent.OutputTuple,
    ClaimOpenEvent.OutputObject
  >;
  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "MerkleRootUpdated"
  ): TypedContractEvent<
    MerkleRootUpdatedEvent.InputTuple,
    MerkleRootUpdatedEvent.OutputTuple,
    MerkleRootUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RegistrationClose"
  ): TypedContractEvent<
    RegistrationCloseEvent.InputTuple,
    RegistrationCloseEvent.OutputTuple,
    RegistrationCloseEvent.OutputObject
  >;
  getEvent(
    key: "RegistrationOpen"
  ): TypedContractEvent<
    RegistrationOpenEvent.InputTuple,
    RegistrationOpenEvent.OutputTuple,
    RegistrationOpenEvent.OutputObject
  >;
  getEvent(
    key: "UserIdentifierRegistered"
  ): TypedContractEvent<
    UserIdentifierRegisteredEvent.InputTuple,
    UserIdentifierRegisteredEvent.OutputTuple,
    UserIdentifierRegisteredEvent.OutputObject
  >;

  filters: {
    "ClaimClose()": TypedContractEvent<
      ClaimCloseEvent.InputTuple,
      ClaimCloseEvent.OutputTuple,
      ClaimCloseEvent.OutputObject
    >;
    ClaimClose: TypedContractEvent<
      ClaimCloseEvent.InputTuple,
      ClaimCloseEvent.OutputTuple,
      ClaimCloseEvent.OutputObject
    >;

    "ClaimOpen()": TypedContractEvent<
      ClaimOpenEvent.InputTuple,
      ClaimOpenEvent.OutputTuple,
      ClaimOpenEvent.OutputObject
    >;
    ClaimOpen: TypedContractEvent<
      ClaimOpenEvent.InputTuple,
      ClaimOpenEvent.OutputTuple,
      ClaimOpenEvent.OutputObject
    >;

    "Claimed(uint256,address,uint256)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "MerkleRootUpdated(bytes32)": TypedContractEvent<
      MerkleRootUpdatedEvent.InputTuple,
      MerkleRootUpdatedEvent.OutputTuple,
      MerkleRootUpdatedEvent.OutputObject
    >;
    MerkleRootUpdated: TypedContractEvent<
      MerkleRootUpdatedEvent.InputTuple,
      MerkleRootUpdatedEvent.OutputTuple,
      MerkleRootUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RegistrationClose()": TypedContractEvent<
      RegistrationCloseEvent.InputTuple,
      RegistrationCloseEvent.OutputTuple,
      RegistrationCloseEvent.OutputObject
    >;
    RegistrationClose: TypedContractEvent<
      RegistrationCloseEvent.InputTuple,
      RegistrationCloseEvent.OutputTuple,
      RegistrationCloseEvent.OutputObject
    >;

    "RegistrationOpen()": TypedContractEvent<
      RegistrationOpenEvent.InputTuple,
      RegistrationOpenEvent.OutputTuple,
      RegistrationOpenEvent.OutputObject
    >;
    RegistrationOpen: TypedContractEvent<
      RegistrationOpenEvent.InputTuple,
      RegistrationOpenEvent.OutputTuple,
      RegistrationOpenEvent.OutputObject
    >;

    "UserIdentifierRegistered(uint256,uint256)": TypedContractEvent<
      UserIdentifierRegisteredEvent.InputTuple,
      UserIdentifierRegisteredEvent.OutputTuple,
      UserIdentifierRegisteredEvent.OutputObject
    >;
    UserIdentifierRegistered: TypedContractEvent<
      UserIdentifierRegisteredEvent.InputTuple,
      UserIdentifierRegisteredEvent.OutputTuple,
      UserIdentifierRegisteredEvent.OutputObject
    >;
  };
}
