#pragma once

#include "awst/Node.h"
#include "awst/WType.h"

#include <map>
#include <memory>
#include <set>
#include <string>
#include <vector>

namespace puyasol::splitter
{

/// Splits oversized subroutine bodies into multiple smaller sub-subroutines.
///
/// When a single function's body exceeds the AVM size limit, this class
/// partitions its statements into sequential chunks, each becoming a new
/// subroutine. Live variables are threaded between chunks via arguments
/// and tuple returns.
class FunctionSplitter
{
public:
	struct SplitResult
	{
		/// New sub-subroutines generated by splitting (the chunks).
		std::vector<std::shared_ptr<awst::Subroutine>> newSubroutines;

		/// Names of functions that were split (the original parent functions).
		std::set<std::string> rewrittenFunctions;

		/// Functions whose chunks modify ReferenceArray parameters
		/// (chunks must stay in same partition for correctness).
		std::set<std::string> mutableSharedFunctions;

		/// Whether any function was actually split.
		bool didSplit = false;
	};

	/// Split oversized subroutines in the given roots vector.
	/// New sub-subroutines are appended to _roots.
	/// Original oversized subroutines are rewritten to call the chunks.
	SplitResult splitOversizedFunctions(
		std::vector<std::shared_ptr<awst::RootNode>>& _roots,
		size_t _maxFunctionInstructions
	);

private:
	/// Info about a single statement for splitting analysis.
	struct StmtInfo
	{
		size_t cost = 0;
		std::set<std::string> defs;  // variables assigned by this statement
		std::set<std::string> uses;  // variables referenced in this statement
	};

	/// A variable with its type, for threading between chunks.
	struct VarInfo
	{
		std::string name;
		awst::WType const* wtype = nullptr;
	};

	/// Analyze each statement in a body: cost + variable defs/uses.
	std::vector<StmtInfo> analyzeStatements(
		std::vector<std::shared_ptr<awst::Statement>> const& _stmts
	);

	/// Find split point indices given per-statement costs and a max chunk cost.
	/// Returns indices where the split should occur (start of next chunk).
	std::vector<size_t> findSplitPoints(
		std::vector<StmtInfo> const& _infos,
		size_t _maxCost
	);

	/// Compute variables that are live across a split point.
	/// These are variables defined before the split and used after it
	/// (excluding function parameters, which are always available).
	std::vector<VarInfo> computeLiveVars(
		std::vector<StmtInfo> const& _infos,
		size_t _splitPoint,
		std::set<std::string> const& _paramNames
	);

	/// Split a single function into chunks. Returns the new chunk subroutines.
	/// The original function's body is rewritten to call the chunks.
	/// _subById provides callee body info for dep-aware per-statement costs.
	std::vector<std::shared_ptr<awst::Subroutine>> splitFunction(
		std::shared_ptr<awst::Subroutine> _func,
		size_t _maxCost,
		std::map<std::string, awst::Subroutine const*> const& _subById = {}
	);

	/// Check whether any chunk of a split function modifies a ReferenceArray parameter.
	/// If so, the chunks must stay in the same partition for correctness.
	bool hasMutableSharedParams(
		awst::Subroutine const& _func,
		std::vector<std::shared_ptr<awst::Subroutine>> const& _chunks
	);

	/// Info about a single write to a ReferenceArray parameter via IndexExpression.
	struct RefParamWrite
	{
		std::string paramName;    // e.g. "evals"
		int index;                // e.g. 13
		std::string localVarName; // e.g. "_evals_13"
		awst::WType const* wtype = nullptr; // element type
	};

	/// Collect IndexExpression writes to ReferenceArray params in a block's statements.
	std::vector<RefParamWrite> collectRefParamWrites(
		awst::Block const& _body,
		std::set<std::string> const& _refParamNames
	);

	/// Convert mutable-shared chunks to value-based I/O.
	/// Replaces IndexExpression writes to ReferenceArray params with local vars
	/// returned in the chunk's tuple. Removes ref params from chunk args.
	/// Rebuilds parent dispatch with writeback assignments.
	void convertToValueBasedIO(
		std::shared_ptr<awst::Subroutine> _parent,
		std::vector<std::shared_ptr<awst::Subroutine>>& _chunks
	);

	/// Check if a statement writes to a FieldExpression/IndexExpression
	/// whose base is one of the given ReferenceArray parameter names.
	bool stmtModifiesRefParam(
		awst::Statement const& _stmt,
		std::set<std::string> const& _refParamNames
	);

	/// Check if an expression target is a write to a ReferenceArray param.
	bool exprModifiesRefParam(
		awst::Expression const& _expr,
		std::set<std::string> const& _refParamNames
	);

	/// Expand calls to rewritten functions by inlining the rewritten body.
	/// This turns 1 statement (call to rewritten func) into N statements
	/// (the chunk dispatch calls), enabling further splitting.
	/// Returns true if any expansion was performed.
	bool expandRewrittenCallees(
		std::shared_ptr<awst::Subroutine> _func,
		std::set<std::string> const& _rewrittenFunctions,
		std::vector<std::shared_ptr<awst::RootNode>> const& _roots
	);

	// ── Callee collection for dep-aware cost estimation ──

	/// Collect SubroutineCallExpression target IDs from a statement tree.
	static void scanStmtForCallees(awst::Statement const& _stmt, std::set<std::string>& _calleeIds);

	/// Collect SubroutineCallExpression target IDs from an expression tree.
	static void scanExprForCallees(awst::Expression const& _expr, std::set<std::string>& _calleeIds);

	// ── Variable collection helpers ──

	/// Collect all VarExpression names referenced in an expression.
	void collectExprUses(awst::Expression const& _expr, std::set<std::string>& _uses);

	/// Collect all VarExpression names referenced in a statement.
	void collectStmtUses(awst::Statement const& _stmt, std::set<std::string>& _uses);

	/// Collect variables defined (assigned to) in a statement.
	void collectStmtDefs(awst::Statement const& _stmt, std::set<std::string>& _defs);

	/// Collect variable types from expressions.
	void collectVarType(awst::Expression const& _expr);

	/// Map of variable name → type, populated during analysis.
	std::map<std::string, awst::WType const*> m_varTypes;

	/// Unique ID counter for SingleEvaluation nodes.
	int m_nextSingleEvalId = 10000;
};

} // namespace puyasol::splitter
