// SPDX-License-Identifier: Apache-2.0
// Copyright 2024 Aztec Labs.
// Verification key for circuits/add2 (c = x + y), generated by
// bb 5.0.0-nightly.20260522 with `-t evm-no-zk` (UltraKeccakHonk, non-ZK).
// Reshaped from `bb write_solidity_verifier` output into the modular keys/ format
// that instance/Add2Honk.sol imports. Regenerate from bb; do not hand-edit.
pragma solidity >=0.8.27;

import {Honk} from "./../HonkTypes.sol";

uint256 constant N = 32;
uint256 constant LOG_N = 5;
uint256 constant NUMBER_OF_PUBLIC_INPUTS = 11;
uint256 constant VK_HASH = 0x19f5d2544fa9e079acd64ba83d4dc7af9290dd3874c86357a73249bc0420c8ca;
library Add2HonkVerificationKey {
    function loadVerificationKey() internal pure returns (Honk.VerificationKey memory) {
        Honk.VerificationKey memory vk = Honk.VerificationKey({
            circuitSize: uint256(32),
            logCircuitSize: uint256(5),
            publicInputsSize: uint256(11),
            ql: Honk.G1Point({ 
               x: uint256(0x07621948420349551c41bf469e75eb0a62c83c46525289ed9995c17eaaf5a538),
               y: uint256(0x06a1a8879ff49997cb550e6defa4c26e2b08c8550a12b810ae6523ff6c2ff152)
            }),
            qr: Honk.G1Point({ 
               x: uint256(0x0ca0bc4b1cd9eadbbf49eae56a99a4502ef13d965226a634d0981555e4a4da56),
               y: uint256(0x15d9cce474cfa99cc8ad1bc386c4c2958cac003ddaec9b174e783329be1b90d3)
            }),
            qo: Honk.G1Point({ 
               x: uint256(0x0ca0bc4b1cd9eadbbf49eae56a99a4502ef13d965226a634d0981555e4a4da56),
               y: uint256(0x1a8a818e6c61f68cefa329f2fabc95c80ad56a538d852f75eda858ed1a616c74)
            }),
            q4: Honk.G1Point({ 
               x: uint256(0x0000000000000000000000000000000000000000000000000000000000000000),
               y: uint256(0x0000000000000000000000000000000000000000000000000000000000000000)
            }),
            qm: Honk.G1Point({ 
               x: uint256(0x0000000000000000000000000000000000000000000000000000000000000000),
               y: uint256(0x0000000000000000000000000000000000000000000000000000000000000000)
            }),
            qc: Honk.G1Point({ 
               x: uint256(0x0000000000000000000000000000000000000000000000000000000000000000),
               y: uint256(0x0000000000000000000000000000000000000000000000000000000000000000)
            }),
            qLookup: Honk.G1Point({ 
               x: uint256(0x0000000000000000000000000000000000000000000000000000000000000000),
               y: uint256(0x0000000000000000000000000000000000000000000000000000000000000000)
            }),
            qArith: Honk.G1Point({ 
               x: uint256(0x17120915850f5d3bfab6b230643da5c73c92c3f695f4b6933c652e775c16198b),
               y: uint256(0x1ad1a9867c0acc38807704abe994f3f91ee791b0b3b9e1d6b40c3f6f35b3a25b)
            }),
            qDeltaRange: Honk.G1Point({ 
               x: uint256(0x0000000000000000000000000000000000000000000000000000000000000000),
               y: uint256(0x0000000000000000000000000000000000000000000000000000000000000000)
            }),
            qElliptic: Honk.G1Point({ 
               x: uint256(0x0000000000000000000000000000000000000000000000000000000000000000),
               y: uint256(0x0000000000000000000000000000000000000000000000000000000000000000)
            }),
            qMemory: Honk.G1Point({ 
               x: uint256(0x0000000000000000000000000000000000000000000000000000000000000000),
               y: uint256(0x0000000000000000000000000000000000000000000000000000000000000000)
            }),
            qNnf: Honk.G1Point({ 
               x: uint256(0x0000000000000000000000000000000000000000000000000000000000000000),
               y: uint256(0x0000000000000000000000000000000000000000000000000000000000000000)
            }),
            qPoseidon2External: Honk.G1Point({ 
               x: uint256(0x0000000000000000000000000000000000000000000000000000000000000000),
               y: uint256(0x0000000000000000000000000000000000000000000000000000000000000000)
            }),
            qPoseidon2Internal: Honk.G1Point({ 
               x: uint256(0x0000000000000000000000000000000000000000000000000000000000000000),
               y: uint256(0x0000000000000000000000000000000000000000000000000000000000000000)
            }),
            s1: Honk.G1Point({ 
               x: uint256(0x271a19b1ececfc56486c686fb3d0d8c6a3c707e3858f7cc432a0d2c01ed930c4),
               y: uint256(0x2e7f2b36b348225e78bc755439e419253437ecb39a6ef464640ea026be002938)
            }),
            s2: Honk.G1Point({ 
               x: uint256(0x0b16524a3e1f0982d37871a8c1d3c8a9f1673bf1cf2dc6d735701eca1029a0b2),
               y: uint256(0x0f24414968c12efffbb0ab00a50a3632470ac0a896ceac29ed586fc057815df0)
            }),
            s3: Honk.G1Point({ 
               x: uint256(0x16471027607fab306447619c93e42fce1abbef23f71e53892fff34dcc418c846),
               y: uint256(0x19adfaa03a5ddf2a49bb833e894b6fe1726e547d6425892b1bfbddf66343841a)
            }),
            s4: Honk.G1Point({ 
               x: uint256(0x28c7e9b240bb4c26a3d2d6a878bfd4e2be06e7e44f9cb80b54195c7dd4eb8a34),
               y: uint256(0x2429eb8490c0f300b994e5454559acd7798a9bc7c1afd4492d6cd51df014e8a9)
            }),
            t1: Honk.G1Point({ 
               x: uint256(0x0000000000000000000000000000000000000000000000000000000000000000),
               y: uint256(0x0000000000000000000000000000000000000000000000000000000000000000)
            }),
            t2: Honk.G1Point({ 
               x: uint256(0x0000000000000000000000000000000000000000000000000000000000000000),
               y: uint256(0x0000000000000000000000000000000000000000000000000000000000000000)
            }),
            t3: Honk.G1Point({ 
               x: uint256(0x0000000000000000000000000000000000000000000000000000000000000000),
               y: uint256(0x0000000000000000000000000000000000000000000000000000000000000000)
            }),
            t4: Honk.G1Point({ 
               x: uint256(0x0000000000000000000000000000000000000000000000000000000000000000),
               y: uint256(0x0000000000000000000000000000000000000000000000000000000000000000)
            }),
            id1: Honk.G1Point({ 
               x: uint256(0x180fa8df8286e7b60f6892063ded93d034849274a8d5e686d19c0a916b54e957),
               y: uint256(0x00fe504f0bdb90471ed75e52672c17cd31b3548ea57c97b57b58822dd916ba2b)
            }),
            id2: Honk.G1Point({ 
               x: uint256(0x1e3db64658561e3614aa4afac768541e14f17d6bdf723716bb256d3f97e0d5c5),
               y: uint256(0x003fb7eb264d997bc0ffda22bea600819c1055d7000bc01b5814b926f5c07abb)
            }),
            id3: Honk.G1Point({ 
               x: uint256(0x0e1f6dffe5d518137bf5ced36714518b6f47213a1c9dd5a7050d10a0c0c4eaa4),
               y: uint256(0x035aa0e34099e83ee07de192d37ea208d723b83a7b3860195941f8814a10337e)
            }),
            id4: Honk.G1Point({ 
               x: uint256(0x039ad6c25d05484be91e2b92b398c00b6780bc24f19d0f5c6e1a52518310dd4d),
               y: uint256(0x0f18e8e06a1e62c65b88ff9096574fea091c7d66049a8fef7ebf2b416d05441a)
            }),
            lagrangeFirst: Honk.G1Point({ 
               x: uint256(0x2a56ce41f6b0be13b9c26747621b821eee81b23a887f299049b14c11e98460d6),
               y: uint256(0x1aa98f2de3ddda547d8f6de4e725ded5827d6338c78656c0d12ca1aea6ef2c7c)
            }),
            lagrangeLast: Honk.G1Point({ 
               x: uint256(0x2531a51ad54f124d58094b219818d2c9f189f2a91aeb664ce376d8b157ba98f8),
               y: uint256(0x272da4396fb2a7ee0638b9140e523def1e6db71809307f677677e62b4163f556)
            })
        });
        return vk;
    }
}
