/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  CircuitAttributeHandlerV2,
  CircuitAttributeHandlerV2Interface,
} from "../../../contracts/libraries/CircuitAttributeHandlerV2";

const _abi = [
  {
    inputs: [],
    name: "InsufficientCharcodeLen",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220a19fe6e7522ad4b423549e30bdcec12d9bb60dd34d2e08cb271cb332e43a73de64736f6c634300081c0033";

type CircuitAttributeHandlerV2ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CircuitAttributeHandlerV2ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CircuitAttributeHandlerV2__factory extends ContractFactory {
  constructor(...args: CircuitAttributeHandlerV2ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      CircuitAttributeHandlerV2 & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): CircuitAttributeHandlerV2__factory {
    return super.connect(runner) as CircuitAttributeHandlerV2__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CircuitAttributeHandlerV2Interface {
    return new Interface(_abi) as CircuitAttributeHandlerV2Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): CircuitAttributeHandlerV2 {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as CircuitAttributeHandlerV2;
  }
}
