/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IKycRegisterCircuitVerifier,
  IKycRegisterCircuitVerifierInterface,
} from "../../../../contracts/interfaces/IRegisterCircuitVerifier.sol/IKycRegisterCircuitVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "a",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "b",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "c",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[4]",
        name: "pubSignals",
        type: "uint256[4]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "isValid",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IKycRegisterCircuitVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IKycRegisterCircuitVerifierInterface {
    return new Interface(_abi) as IKycRegisterCircuitVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IKycRegisterCircuitVerifier {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IKycRegisterCircuitVerifier;
  }
}
