/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPoseidonT3,
  IPoseidonT3Interface,
} from "../../../contracts/interfaces/IPoseidonT3";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "inputs",
        type: "uint256[2]",
      },
    ],
    name: "hash",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class IPoseidonT3__factory {
  static readonly abi = _abi;
  static createInterface(): IPoseidonT3Interface {
    return new Interface(_abi) as IPoseidonT3Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPoseidonT3 {
    return new Contract(address, _abi, runner) as unknown as IPoseidonT3;
  }
}
