/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAadhaarRegisterCircuitVerifier,
  IAadhaarRegisterCircuitVerifierInterface,
} from "../../../../contracts/interfaces/IRegisterCircuitVerifier.sol/IAadhaarRegisterCircuitVerifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "a",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "b",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "c",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[4]",
        name: "pubSignals",
        type: "uint256[4]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "isValid",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAadhaarRegisterCircuitVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): IAadhaarRegisterCircuitVerifierInterface {
    return new Interface(_abi) as IAadhaarRegisterCircuitVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAadhaarRegisterCircuitVerifier {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAadhaarRegisterCircuitVerifier;
  }
}
