"""
M21: Groth16 zk-SNARK Verifier — Poseidon Hash Preimage (243 constraints).
Exercises: Verification of a real cryptographic hash circuit (circomlib Poseidon).

Circuit: Poseidon hash preimage proof
  - Private inputs: preimage[0]=123, preimage[1]=456
  - Public output: hash = Poseidon(123, 456)
  - 243 non-linear constraints (vs 1-7 in M18-M20)

Proof generated with snarkjs (Groth16, BN128/BN254 curve).
Verifier Solidity code generated by `snarkjs zkey export solidityverifier`.
"""

import pytest
import algokit_utils as au
from algokit_utils.models.account import SigningAccount

from conftest import deploy_contract


OPUP_FEE = au.AlgoAmount(micro_algo=100_000)

# Valid Groth16 proof for Poseidon(123, 456) = 19620391833206800292073497099357851348339828238212863168390691880932172496143
PROOF_A = [
    12016724999792277373915008240491650569066282092748425451838839880707649820852,
    15642078320736370418071084798942077298276928656472315303274092407334386642284,
]

# pi_b with EVM coordinate swap: [x_im, x_re, y_im, y_re]
PROOF_B = [
    19603636679429065352922659439203213572382211898220488525448198899731266629889,  # x_im
    10527263488018862201327252854946077436499563096772954049789326687505086224350,  # x_re
    1695487672840860704599891334538696779135685808743866802544343802514588953091,   # y_im
    3388521507770867383144583822040710553639375890017805861029738285493568823125,   # y_re
]

PROOF_C = [
    16267245738779053621406855107071800557255418847672904155257028553011712917013,
    8030219157381089833896809144417790060439776249448468757901915508237594723581,
]

# Poseidon(123, 456)
POSEIDON_HASH = 19620391833206800292073497099357851348339828238212863168390691880932172496143
PUB_SIGNALS = [POSEIDON_HASH]

BN254_R = 21888242871839275222246405745257275088548364400416034343698204186575808495617


@pytest.fixture(scope="module")
def verifier_client(
    localnet: au.AlgorandClient, account: SigningAccount
) -> au.AppClient:
    """Deploy the PoseidonVerifier contract."""
    return deploy_contract(localnet, account, "PoseidonVerifier")


@pytest.mark.localnet
def test_verifier_deploys(verifier_client: au.AppClient) -> None:
    """The Poseidon verifier deploys successfully."""
    assert verifier_client.app_id > 0


@pytest.mark.localnet
def test_valid_proof_returns_true(verifier_client: au.AppClient) -> None:
    """A valid Poseidon hash preimage proof should be accepted."""
    result = verifier_client.send.call(
        au.AppClientMethodCallParams(
            method="verifyProof",
            static_fee=OPUP_FEE,
            args=[PROOF_A, PROOF_B, PROOF_C, PUB_SIGNALS],
        )
    )
    assert result.abi_return is True


@pytest.mark.localnet
def test_wrong_hash_returns_false(verifier_client: au.AppClient) -> None:
    """Wrong hash value should fail (not the real Poseidon output)."""
    result = verifier_client.send.call(
        au.AppClientMethodCallParams(
            method="verifyProof",
            static_fee=OPUP_FEE,
            args=[PROOF_A, PROOF_B, PROOF_C, [POSEIDON_HASH + 1]],
        )
    )
    assert result.abi_return is False


@pytest.mark.localnet
def test_zero_hash_returns_false(verifier_client: au.AppClient) -> None:
    """Zero as hash value should fail."""
    result = verifier_client.send.call(
        au.AppClientMethodCallParams(
            method="verifyProof",
            static_fee=OPUP_FEE,
            args=[PROOF_A, PROOF_B, PROOF_C, [0]],
        )
    )
    assert result.abi_return is False


@pytest.mark.localnet
def test_tampered_proof_a_returns_false(verifier_client: au.AppClient) -> None:
    """Modifying proof point A should fail."""
    tampered_a = [PROOF_A[0] + 1, PROOF_A[1]]
    try:
        result = verifier_client.send.call(
            au.AppClientMethodCallParams(
                method="verifyProof",
                static_fee=OPUP_FEE,
                args=[tampered_a, PROOF_B, PROOF_C, PUB_SIGNALS],
            )
        )
        assert result.abi_return is False
    except Exception:
        pass


@pytest.mark.localnet
def test_tampered_proof_b_returns_false(verifier_client: au.AppClient) -> None:
    """Modifying proof point B (G2) should fail."""
    tampered_b = [PROOF_B[0], PROOF_B[1], PROOF_B[2] + 1, PROOF_B[3]]
    try:
        result = verifier_client.send.call(
            au.AppClientMethodCallParams(
                method="verifyProof",
                static_fee=OPUP_FEE,
                args=[PROOF_A, tampered_b, PROOF_C, PUB_SIGNALS],
            )
        )
        assert result.abi_return is False
    except Exception:
        pass


@pytest.mark.localnet
def test_tampered_proof_c_returns_false(verifier_client: au.AppClient) -> None:
    """Modifying proof point C should fail."""
    tampered_c = [PROOF_C[0], PROOF_C[1] + 1]
    try:
        result = verifier_client.send.call(
            au.AppClientMethodCallParams(
                method="verifyProof",
                static_fee=OPUP_FEE,
                args=[PROOF_A, PROOF_B, tampered_c, PUB_SIGNALS],
            )
        )
        assert result.abi_return is False
    except Exception:
        pass


@pytest.mark.localnet
def test_signal_at_field_boundary(verifier_client: au.AppClient) -> None:
    """Signal == r should be rejected by checkField."""
    result = verifier_client.send.call(
        au.AppClientMethodCallParams(
            method="verifyProof",
            static_fee=OPUP_FEE,
            args=[PROOF_A, PROOF_B, PROOF_C, [BN254_R]],
        )
    )
    assert result.abi_return is False


@pytest.mark.localnet
def test_signal_just_below_boundary(verifier_client: au.AppClient) -> None:
    """Signal == r-1 passes checkField but fails pairing (wrong value)."""
    result = verifier_client.send.call(
        au.AppClientMethodCallParams(
            method="verifyProof",
            static_fee=OPUP_FEE,
            args=[PROOF_A, PROOF_B, PROOF_C, [BN254_R - 1]],
        )
    )
    assert result.abi_return is False


@pytest.mark.localnet
def test_all_zero_proof(verifier_client: au.AppClient) -> None:
    """All-zero proof should be rejected."""
    try:
        result = verifier_client.send.call(
            au.AppClientMethodCallParams(
                method="verifyProof",
                static_fee=OPUP_FEE,
                args=[[0, 0], [0, 0, 0, 0], [0, 0], PUB_SIGNALS],
            )
        )
        assert result.abi_return is False
    except Exception:
        pass


@pytest.mark.localnet
def test_multiplier_proof_rejected(verifier_client: au.AppClient) -> None:
    """Proof from multiplier circuit should fail on Poseidon verifier (cross-verifier)."""
    mult_a = [
        2820903531187837128616678014576451074808907135754885058308058066621396041846,
        16096969730104392443397683640049842112213680785663556658688811764068002964331,
    ]
    mult_b = [
        21351900782231288160774380381247769854822499614316084382526506344590048916443,
        21585881999632066401196508170928557624769075476274389821685610036164618548561,
        2940141159635478829518720708162929838328073871962631470445822823156256904171,
        9625345631143102525774527358845509412805565781642520986146921130734766416034,
    ]
    mult_c = [
        6587110300090488253894481492180403298038217352224006937131269045223050037347,
        14999160429273035898893805233111666279009217854885302266072997539546670342201,
    ]
    try:
        result = verifier_client.send.call(
            au.AppClientMethodCallParams(
                method="verifyProof",
                static_fee=OPUP_FEE,
                args=[mult_a, mult_b, mult_c, [33]],
            )
        )
        assert result.abi_return is False
    except Exception:
        pass
