"""
M18: Groth16 zk-SNARK Verifier with valid proof test.
Exercises: End-to-end Groth16 proof verification on AVM.

Circuit: simple multiplier (a * b == c)
  - Private inputs: a=3, b=11
  - Public output: c=33

Proof generated with snarkjs (Groth16, BN128/BN254 curve).
Verifier Solidity code generated by `snarkjs zkey export solidityverifier`.
"""

import pytest
import algokit_utils as au
from algokit_utils.models.account import SigningAccount

from conftest import deploy_contract


# Fee to cover inner transactions for opup budget pooling.
OPUP_FEE = au.AlgoAmount(micro_algo=100_000)

# Valid Groth16 proof for the multiplier circuit (3 * 11 == 33).
# Generated by: snarkjs groth16 fullprove input.json multiplier.wasm multiplier.zkey
#
# The Solidity verifier expects: verifyProof(uint[2] _pA, uint[2][2] _pB, uint[2] _pC, uint[1] _pubSignals)
# Our ABI encodes these as: (uint512[2], uint512[4], uint512[2], uint512[1])

# Proof point A (G1 point)
PROOF_A = [
    2820903531187837128616678014576451074808907135754885058308058066621396041846,
    16096969730104392443397683640049842112213680785663556658688811764068002964331,
]

# Proof point B (G2 point).
# snarkjs proof.json stores pi_b as [[x_real, x_imaginary], [y_real, y_imaginary]].
# The Solidity verifier's calldata expects EVM precompile ordering:
#   _pB[0][0]=x_im, _pB[0][1]=x_re, _pB[1][0]=y_im, _pB[1][1]=y_re
# So we must swap within each pair: [pi_b[0][1], pi_b[0][0], pi_b[1][1], pi_b[1][0]]
PROOF_B = [
    21351900782231288160774380381247769854822499614316084382526506344590048916443,  # x_im
    21585881999632066401196508170928557624769075476274389821685610036164618548561,  # x_re
    2940141159635478829518720708162929838328073871962631470445822823156256904171,   # y_im
    9625345631143102525774527358845509412805565781642520986146921130734766416034,   # y_re
]

# Proof point C (G1 point)
PROOF_C = [
    6587110300090488253894481492180403298038217352224006937131269045223050037347,
    14999160429273035898893805233111666279009217854885302266072997539546670342201,
]

# Public signals (just the output c=33)
PUB_SIGNALS = [33]

# BN254 scalar field order
BN254_R = 21888242871839275222246405745257275088548364400416034343698204186575808495617


@pytest.fixture(scope="module")
def verifier_client(
    localnet: au.AlgorandClient, account: SigningAccount
) -> au.AppClient:
    """Deploy the Groth16Verifier contract (simple multiplier circuit)."""
    client = deploy_contract(
        localnet, account, "Groth16Verifier"
    )
    return client


@pytest.mark.localnet
def test_verifier_deploys(verifier_client: au.AppClient) -> None:
    """The Groth16 verifier contract deploys successfully."""
    assert verifier_client.app_id > 0


@pytest.mark.localnet
def test_valid_proof_returns_true(verifier_client: au.AppClient) -> None:
    """A valid Groth16 proof (3 * 11 == 33) should be accepted by the verifier."""
    result = verifier_client.send.call(
        au.AppClientMethodCallParams(
            method="verifyProof",
            static_fee=OPUP_FEE,
            args=[PROOF_A, PROOF_B, PROOF_C, PUB_SIGNALS],
        )
    )
    assert result.abi_return is True


@pytest.mark.localnet
def test_wrong_public_signal_returns_false(verifier_client: au.AppClient) -> None:
    """The same proof but with a wrong public signal (34 instead of 33) should fail."""
    result = verifier_client.send.call(
        au.AppClientMethodCallParams(
            method="verifyProof",
            static_fee=OPUP_FEE,
            args=[PROOF_A, PROOF_B, PROOF_C, [34]],
        )
    )
    assert result.abi_return is False


@pytest.mark.localnet
def test_tampered_proof_a_returns_false(verifier_client: au.AppClient) -> None:
    """Modifying proof point A should make the proof invalid."""
    tampered_a = [PROOF_A[0] + 1, PROOF_A[1]]
    try:
        result = verifier_client.send.call(
            au.AppClientMethodCallParams(
                method="verifyProof",
                static_fee=OPUP_FEE,
                args=[tampered_a, PROOF_B, PROOF_C, PUB_SIGNALS],
            )
        )
        # If it returns, it must be false
        assert result.abi_return is False
    except Exception:
        # AVM may abort on invalid curve points - this is also correct rejection
        pass


@pytest.mark.localnet
def test_tampered_proof_c_returns_false(verifier_client: au.AppClient) -> None:
    """Modifying proof point C should make the proof invalid."""
    tampered_c = [PROOF_C[0], PROOF_C[1] + 1]
    try:
        result = verifier_client.send.call(
            au.AppClientMethodCallParams(
                method="verifyProof",
                static_fee=OPUP_FEE,
                args=[PROOF_A, PROOF_B, tampered_c, PUB_SIGNALS],
            )
        )
        assert result.abi_return is False
    except Exception:
        pass


@pytest.mark.localnet
def test_signal_out_of_range_returns_false(verifier_client: au.AppClient) -> None:
    """A public signal >= r (scalar field order) should be rejected by checkField."""
    result = verifier_client.send.call(
        au.AppClientMethodCallParams(
            method="verifyProof",
            static_fee=OPUP_FEE,
            args=[PROOF_A, PROOF_B, PROOF_C, [BN254_R]],
        )
    )
    assert result.abi_return is False
