"""
M20: Groth16 zk-SNARK Verifier — Range Proof (3 public signals).
Exercises: Groth16 proof verification with public inputs + output.

Circuit: range proof with commitment
  - Private input: x=42
  - Public inputs: lo=10, hi=100
  - Public output: commitment=2764  (42*42 + 10*100 = 1764 + 1000)

Proof generated with snarkjs (Groth16, BN128/BN254 curve).
Verifier Solidity code generated by `snarkjs zkey export solidityverifier`.
"""

import pytest
import algokit_utils as au
from algokit_utils.models.account import SigningAccount

from conftest import deploy_contract


# Fee to cover inner transactions for opup budget pooling.
OPUP_FEE = au.AlgoAmount(micro_algo=100_000)

# Valid Groth16 proof for the range proof circuit: x=42, lo=10, hi=100 => commitment=2764
#
# The Solidity verifier expects: verifyProof(uint[2] _pA, uint[2][2] _pB, uint[2] _pC, uint[3] _pubSignals)
# Our ABI encodes these as: (uint512[2], uint512[4], uint512[2], uint512[3])

# Proof point A (G1 point)
PROOF_A = [
    20816211119644969029617143786831413612709137102154993676640158742601315319179,
    16410516247756718797051663501065232764496317257126399449038320343871833625128,
]

# Proof point B (G2 point).
# snarkjs proof.json: pi_b = [[x_re, x_im], [y_re, y_im]]
# Solidity calldata ordering: [x_im, x_re, y_im, y_re]
PROOF_B = [
    10063760694792352700307906962275627984218429753271677921752173096769171019177,  # x_im
    536778060989767340485922767554745473302781953422272052423600617349730624793,    # x_re
    717093117493610433828009870094480267548096870301263710584698610401660569921,    # y_im
    7537615619602896315221814794676019154366407489108881188321264002920660105944,   # y_re
]

# Proof point C (G1 point)
PROOF_C = [
    3502815727984523274485462847690796918934484518396888373439501249892878451808,
    5984270615765655875924558005779667798994083070572403405845387401039237889561,
]

# Public signals: [commitment, lo, hi] = [2764, 10, 100]
PUB_SIGNALS = [2764, 10, 100]

# BN254 scalar field order
BN254_R = 21888242871839275222246405745257275088548364400416034343698204186575808495617


@pytest.fixture(scope="module")
def verifier_client(
    localnet: au.AlgorandClient, account: SigningAccount
) -> au.AppClient:
    """Deploy the RangeProofVerifier contract."""
    client = deploy_contract(
        localnet, account, "RangeProofVerifier"
    )
    return client



@pytest.mark.localnet
def test_verifier_deploys(verifier_client: au.AppClient) -> None:
    """The range proof verifier contract deploys successfully."""
    assert verifier_client.app_id > 0


@pytest.mark.localnet
def test_valid_proof_returns_true(verifier_client: au.AppClient) -> None:
    """A valid Groth16 proof (x=42 in [10,100], commitment=2764) should be accepted."""
    result = verifier_client.send.call(
        au.AppClientMethodCallParams(
            method="verifyProof",
            static_fee=OPUP_FEE,
            args=[PROOF_A, PROOF_B, PROOF_C, PUB_SIGNALS],
        )
    )
    assert result.abi_return is True


@pytest.mark.localnet
def test_wrong_commitment_returns_false(verifier_client: au.AppClient) -> None:
    """Wrong commitment signal (2765 instead of 2764) should fail."""
    result = verifier_client.send.call(
        au.AppClientMethodCallParams(
            method="verifyProof",
            static_fee=OPUP_FEE,
            args=[PROOF_A, PROOF_B, PROOF_C, [2765, 10, 100]],
        )
    )
    assert result.abi_return is False


@pytest.mark.localnet
def test_wrong_lo_returns_false(verifier_client: au.AppClient) -> None:
    """Wrong lo signal (11 instead of 10) should fail."""
    result = verifier_client.send.call(
        au.AppClientMethodCallParams(
            method="verifyProof",
            static_fee=OPUP_FEE,
            args=[PROOF_A, PROOF_B, PROOF_C, [2764, 11, 100]],
        )
    )
    assert result.abi_return is False


@pytest.mark.localnet
def test_wrong_hi_returns_false(verifier_client: au.AppClient) -> None:
    """Wrong hi signal (99 instead of 100) should fail."""
    result = verifier_client.send.call(
        au.AppClientMethodCallParams(
            method="verifyProof",
            static_fee=OPUP_FEE,
            args=[PROOF_A, PROOF_B, PROOF_C, [2764, 10, 99]],
        )
    )
    assert result.abi_return is False


@pytest.mark.localnet
def test_tampered_proof_a_returns_false(verifier_client: au.AppClient) -> None:
    """Modifying proof point A should make the proof invalid."""
    tampered_a = [PROOF_A[0] + 1, PROOF_A[1]]
    try:
        result = verifier_client.send.call(
            au.AppClientMethodCallParams(
                method="verifyProof",
                static_fee=OPUP_FEE,
                args=[tampered_a, PROOF_B, PROOF_C, PUB_SIGNALS],
            )
        )
        assert result.abi_return is False
    except Exception:
        # AVM may abort on invalid curve points
        pass


@pytest.mark.localnet
def test_tampered_proof_b_returns_false(verifier_client: au.AppClient) -> None:
    """Modifying proof point B (G2) should make the proof invalid."""
    tampered_b = [PROOF_B[0], PROOF_B[1] + 1, PROOF_B[2], PROOF_B[3]]
    try:
        result = verifier_client.send.call(
            au.AppClientMethodCallParams(
                method="verifyProof",
                static_fee=OPUP_FEE,
                args=[PROOF_A, tampered_b, PROOF_C, PUB_SIGNALS],
            )
        )
        assert result.abi_return is False
    except Exception:
        pass


@pytest.mark.localnet
def test_tampered_proof_c_returns_false(verifier_client: au.AppClient) -> None:
    """Modifying proof point C should make the proof invalid."""
    tampered_c = [PROOF_C[0] + 1, PROOF_C[1]]
    try:
        result = verifier_client.send.call(
            au.AppClientMethodCallParams(
                method="verifyProof",
                static_fee=OPUP_FEE,
                args=[PROOF_A, PROOF_B, tampered_c, PUB_SIGNALS],
            )
        )
        assert result.abi_return is False
    except Exception:
        pass


@pytest.mark.localnet
def test_signal_at_field_boundary_returns_false(verifier_client: au.AppClient) -> None:
    """A public signal == r (scalar field order) should be rejected by checkField."""
    result = verifier_client.send.call(
        au.AppClientMethodCallParams(
            method="verifyProof",
            static_fee=OPUP_FEE,
            args=[PROOF_A, PROOF_B, PROOF_C, [BN254_R, 10, 100]],
        )
    )
    assert result.abi_return is False


@pytest.mark.localnet
def test_signal_just_below_boundary(verifier_client: au.AppClient) -> None:
    """A public signal == r-1 (max valid field element) should pass checkField but fail pairing."""
    result = verifier_client.send.call(
        au.AppClientMethodCallParams(
            method="verifyProof",
            static_fee=OPUP_FEE,
            args=[PROOF_A, PROOF_B, PROOF_C, [BN254_R - 1, 10, 100]],
        )
    )
    assert result.abi_return is False


@pytest.mark.localnet
def test_all_zero_proof_returns_false(verifier_client: au.AppClient) -> None:
    """An all-zero proof should be rejected."""
    try:
        result = verifier_client.send.call(
            au.AppClientMethodCallParams(
                method="verifyProof",
                static_fee=OPUP_FEE,
                args=[[0, 0], [0, 0, 0, 0], [0, 0], PUB_SIGNALS],
            )
        )
        assert result.abi_return is False
    except Exception:
        pass


@pytest.mark.localnet
def test_swapped_signals_returns_false(verifier_client: au.AppClient) -> None:
    """Correct signal values in wrong order should fail."""
    # Swap commitment and lo: [10, 2764, 100] instead of [2764, 10, 100]
    result = verifier_client.send.call(
        au.AppClientMethodCallParams(
            method="verifyProof",
            static_fee=OPUP_FEE,
            args=[PROOF_A, PROOF_B, PROOF_C, [10, 2764, 100]],
        )
    )
    assert result.abi_return is False


@pytest.mark.localnet
def test_cubic_proof_rejected_by_range_verifier(
    verifier_client: au.AppClient,
) -> None:
    """A valid proof from the cubic circuit should be rejected by the range proof verifier.
    Cross-verifier test: different circuit = different verification key."""
    # Cubic proof data from M19 (x=3 => x_squared=9, out=35)
    cubic_a = [
        20142427103495202266623424121043479452086952303398912120731053310801168029892,
        21060701563274264777658945006569193248376894993427505504969620598851046616485,
    ]
    cubic_b = [
        11901938039824042547758149454649453111920217742316873349906392712222983193512,
        1834208190963832174832328243361036530400386058289516545926365898408117830923,
        656860124753310523101161255141728882762758473959667298185180333069376361516,
        17247340835423360867365245738680229618462115856823208869308222146182427202420,
    ]
    cubic_c = [
        14595750151648228275740126844143189511207649022728075877149322434777090801262,
        12939167655551808341801852990815469170642473668580083841683356130944356377968,
    ]
    try:
        result = verifier_client.send.call(
            au.AppClientMethodCallParams(
                method="verifyProof",
                static_fee=OPUP_FEE,
                args=[cubic_a, cubic_b, cubic_c, [9, 35, 0]],
            )
        )
        assert result.abi_return is False
    except Exception:
        pass


@pytest.mark.localnet
def test_multiplier_proof_rejected_by_range_verifier(
    verifier_client: au.AppClient,
) -> None:
    """A valid proof from the multiplier circuit should be rejected by the range proof verifier.
    Cross-verifier test: different circuit = different verification key."""
    # Multiplier proof data from M18 (3 * 11 == 33)
    multiplier_a = [
        2820903531187837128616678014576451074808907135754885058308058066621396041846,
        16096969730104392443397683640049842112213680785663556658688811764068002964331,
    ]
    multiplier_b = [
        21351900782231288160774380381247769854822499614316084382526506344590048916443,
        21585881999632066401196508170928557624769075476274389821685610036164618548561,
        2940141159635478829518720708162929838328073871962631470445822823156256904171,
        9625345631143102525774527358845509412805565781642520986146921130734766416034,
    ]
    multiplier_c = [
        6587110300090488253894481492180403298038217352224006937131269045223050037347,
        14999160429273035898893805233111666279009217854885302266072997539546670342201,
    ]
    try:
        result = verifier_client.send.call(
            au.AppClientMethodCallParams(
                method="verifyProof",
                static_fee=OPUP_FEE,
                args=[multiplier_a, multiplier_b, multiplier_c, [33, 0, 0]],
            )
        )
        assert result.abi_return is False
    except Exception:
        pass
