"""
M19: Groth16 zk-SNARK Verifier — Cubic Equation (2 public signals).
Exercises: Groth16 proof verification with multiple public outputs.

Circuit: cubic equation (x^3 + x + 5 == out)
  - Private input: x=3
  - Public outputs: x_squared=9, out=35  (3^2=9, 3^3+3+5=35)

Proof generated with snarkjs (Groth16, BN128/BN254 curve).
Verifier Solidity code generated by `snarkjs zkey export solidityverifier`.
"""

import pytest
import algokit_utils as au
from algokit_utils.models.account import SigningAccount

from conftest import deploy_contract


# Fee to cover inner transactions for opup budget pooling.
OPUP_FEE = au.AlgoAmount(micro_algo=100_000)

# Valid Groth16 proof for the cubic circuit: x=3 => x_squared=9, out=35
#
# The Solidity verifier expects: verifyProof(uint[2] _pA, uint[2][2] _pB, uint[2] _pC, uint[2] _pubSignals)
# Our ABI encodes these as: (uint512[2], uint512[4], uint512[2], uint512[2])

# Proof point A (G1 point)
PROOF_A = [
    20142427103495202266623424121043479452086952303398912120731053310801168029892,
    21060701563274264777658945006569193248376894993427505504969620598851046616485,
]

# Proof point B (G2 point).
# snarkjs proof.json stores pi_b as [[x_real, x_imaginary], [y_real, y_imaginary]].
# The Solidity verifier's calldata expects EVM precompile ordering:
#   _pB[0][0]=x_im, _pB[0][1]=x_re, _pB[1][0]=y_im, _pB[1][1]=y_re
# So we must swap within each pair: [pi_b[0][1], pi_b[0][0], pi_b[1][1], pi_b[1][0]]
PROOF_B = [
    11901938039824042547758149454649453111920217742316873349906392712222983193512,  # x_im
    1834208190963832174832328243361036530400386058289516545926365898408117830923,   # x_re
    656860124753310523101161255141728882762758473959667298185180333069376361516,    # y_im
    17247340835423360867365245738680229618462115856823208869308222146182427202420,  # y_re
]

# Proof point C (G1 point)
PROOF_C = [
    14595750151648228275740126844143189511207649022728075877149322434777090801262,
    12939167655551808341801852990815469170642473668580083841683356130944356377968,
]

# Public signals: [x_squared, out] = [9, 35]
PUB_SIGNALS = [9, 35]

# BN254 scalar field order
BN254_R = 21888242871839275222246405745257275088548364400416034343698204186575808495617


@pytest.fixture(scope="module")
def verifier_client(
    localnet: au.AlgorandClient, account: SigningAccount
) -> au.AppClient:
    """Deploy the CubicVerifier contract."""
    client = deploy_contract(
        localnet, account, "CubicVerifier"
    )
    return client


@pytest.mark.localnet
def test_verifier_deploys(verifier_client: au.AppClient) -> None:
    """The cubic verifier contract deploys successfully."""
    assert verifier_client.app_id > 0


@pytest.mark.localnet
def test_valid_proof_returns_true(verifier_client: au.AppClient) -> None:
    """A valid Groth16 proof (x=3 => x_squared=9, out=35) should be accepted."""
    result = verifier_client.send.call(
        au.AppClientMethodCallParams(
            method="verifyProof",
            static_fee=OPUP_FEE,
            args=[PROOF_A, PROOF_B, PROOF_C, PUB_SIGNALS],
        )
    )
    assert result.abi_return is True


@pytest.mark.localnet
def test_wrong_first_signal_returns_false(verifier_client: au.AppClient) -> None:
    """Wrong x_squared signal (10 instead of 9) should fail verification."""
    result = verifier_client.send.call(
        au.AppClientMethodCallParams(
            method="verifyProof",
            static_fee=OPUP_FEE,
            args=[PROOF_A, PROOF_B, PROOF_C, [10, 35]],
        )
    )
    assert result.abi_return is False


@pytest.mark.localnet
def test_wrong_second_signal_returns_false(verifier_client: au.AppClient) -> None:
    """Wrong out signal (36 instead of 35) should fail verification."""
    result = verifier_client.send.call(
        au.AppClientMethodCallParams(
            method="verifyProof",
            static_fee=OPUP_FEE,
            args=[PROOF_A, PROOF_B, PROOF_C, [9, 36]],
        )
    )
    assert result.abi_return is False


@pytest.mark.localnet
def test_tampered_proof_a_returns_false(verifier_client: au.AppClient) -> None:
    """Modifying proof point A should make the proof invalid."""
    tampered_a = [PROOF_A[0] + 1, PROOF_A[1]]
    try:
        result = verifier_client.send.call(
            au.AppClientMethodCallParams(
                method="verifyProof",
                static_fee=OPUP_FEE,
                args=[tampered_a, PROOF_B, PROOF_C, PUB_SIGNALS],
            )
        )
        # If it returns, it must be false
        assert result.abi_return is False
    except Exception:
        # AVM may abort on invalid curve points — this is also correct rejection
        pass


@pytest.mark.localnet
def test_tampered_proof_b_returns_false(verifier_client: au.AppClient) -> None:
    """Modifying proof point B (G2) should make the proof invalid."""
    tampered_b = [PROOF_B[0] + 1, PROOF_B[1], PROOF_B[2], PROOF_B[3]]
    try:
        result = verifier_client.send.call(
            au.AppClientMethodCallParams(
                method="verifyProof",
                static_fee=OPUP_FEE,
                args=[PROOF_A, tampered_b, PROOF_C, PUB_SIGNALS],
            )
        )
        assert result.abi_return is False
    except Exception:
        pass


@pytest.mark.localnet
def test_tampered_proof_c_returns_false(verifier_client: au.AppClient) -> None:
    """Modifying proof point C should make the proof invalid."""
    tampered_c = [PROOF_C[0], PROOF_C[1] + 1]
    try:
        result = verifier_client.send.call(
            au.AppClientMethodCallParams(
                method="verifyProof",
                static_fee=OPUP_FEE,
                args=[PROOF_A, PROOF_B, tampered_c, PUB_SIGNALS],
            )
        )
        assert result.abi_return is False
    except Exception:
        pass


@pytest.mark.localnet
def test_signal_at_field_boundary_returns_false(verifier_client: au.AppClient) -> None:
    """A public signal == r (scalar field order) should be rejected by checkField."""
    result = verifier_client.send.call(
        au.AppClientMethodCallParams(
            method="verifyProof",
            static_fee=OPUP_FEE,
            args=[PROOF_A, PROOF_B, PROOF_C, [BN254_R, 35]],
        )
    )
    assert result.abi_return is False


@pytest.mark.localnet
def test_signal_just_below_boundary(verifier_client: au.AppClient) -> None:
    """A public signal == r-1 (max valid field element) should pass checkField but fail pairing."""
    result = verifier_client.send.call(
        au.AppClientMethodCallParams(
            method="verifyProof",
            static_fee=OPUP_FEE,
            args=[PROOF_A, PROOF_B, PROOF_C, [BN254_R - 1, 35]],
        )
    )
    # Passes checkField but fails pairing (wrong signal value)
    assert result.abi_return is False


@pytest.mark.localnet
def test_all_zero_proof_returns_false(verifier_client: au.AppClient) -> None:
    """An all-zero proof should be rejected."""
    try:
        result = verifier_client.send.call(
            au.AppClientMethodCallParams(
                method="verifyProof",
                static_fee=OPUP_FEE,
                args=[[0, 0], [0, 0, 0, 0], [0, 0], PUB_SIGNALS],
            )
        )
        assert result.abi_return is False
    except Exception:
        # AVM may abort on zero/identity point operations
        pass


@pytest.mark.localnet
def test_swapped_signals_returns_false(verifier_client: au.AppClient) -> None:
    """Correct signal values in wrong order (swapped) should fail."""
    result = verifier_client.send.call(
        au.AppClientMethodCallParams(
            method="verifyProof",
            static_fee=OPUP_FEE,
            args=[PROOF_A, PROOF_B, PROOF_C, [35, 9]],  # swapped: out, x_squared
        )
    )
    assert result.abi_return is False


@pytest.mark.localnet
def test_multiplier_proof_rejected_by_cubic_verifier(
    verifier_client: au.AppClient,
) -> None:
    """A valid proof from the multiplier circuit should be rejected by the cubic verifier.
    Cross-verifier test: different circuit = different verification key."""
    # Multiplier proof data from M18 (3 * 11 == 33)
    multiplier_a = [
        2820903531187837128616678014576451074808907135754885058308058066621396041846,
        16096969730104392443397683640049842112213680785663556658688811764068002964331,
    ]
    multiplier_b = [
        21351900782231288160774380381247769854822499614316084382526506344590048916443,
        21585881999632066401196508170928557624769075476274389821685610036164618548561,
        2940141159635478829518720708162929838328073871962631470445822823156256904171,
        9625345631143102525774527358845509412805565781642520986146921130734766416034,
    ]
    multiplier_c = [
        6587110300090488253894481492180403298038217352224006937131269045223050037347,
        14999160429273035898893805233111666279009217854885302266072997539546670342201,
    ]
    try:
        result = verifier_client.send.call(
            au.AppClientMethodCallParams(
                method="verifyProof",
                static_fee=OPUP_FEE,
                args=[multiplier_a, multiplier_b, multiplier_c, [33, 0]],
            )
        )
        assert result.abi_return is False
    except Exception:
        pass
