// SPDX-License-Identifier: BSD-3-Clause
pragma solidity ^0.8.10;

/// @title Mock Comptroller for CToken testing.
/// Returns 0 (no error) for all allowed checks by default.
contract ComptrollerMock {
    // Explicit function instead of public constant (public constant getters
    // not yet generated by the compiler as ARC4 methods).
    function isComptroller() external pure returns (bool) {
        return true;
    }
    bool public failMint;
    bool public failRedeem;
    bool public failBorrow;
    bool public failRepayBorrow;
    bool public failLiquidateBorrow;
    bool public failSeize;
    bool public failTransfer;

    function setFailMint(bool _fail) external { failMint = _fail; }
    function setFailRedeem(bool _fail) external { failRedeem = _fail; }
    function setFailBorrow(bool _fail) external { failBorrow = _fail; }
    function setFailRepayBorrow(bool _fail) external { failRepayBorrow = _fail; }
    function setFailLiquidateBorrow(bool _fail) external { failLiquidateBorrow = _fail; }
    function setFailSeize(bool _fail) external { failSeize = _fail; }
    function setFailTransfer(bool _fail) external { failTransfer = _fail; }

    function enterMarkets(address[] calldata) external pure returns (uint[] memory) {
        uint[] memory results = new uint[](0);
        return results;
    }

    function mintAllowed(address, address, uint) external view returns (uint) {
        return failMint ? 1 : 0;
    }

    function mintVerify(address, address, uint, uint) external pure {}

    function redeemAllowed(address, address, uint) external view returns (uint) {
        return failRedeem ? 1 : 0;
    }

    function redeemVerify(address, address, uint, uint) external pure {}

    function borrowAllowed(address, address, uint) external view returns (uint) {
        return failBorrow ? 1 : 0;
    }

    function borrowVerify(address, address, uint) external pure {}

    function repayBorrowAllowed(address, address, address, uint) external view returns (uint) {
        return failRepayBorrow ? 1 : 0;
    }

    function repayBorrowVerify(address, address, address, uint, uint) external pure {}

    function liquidateBorrowAllowed(address, address, address, address, uint) external view returns (uint) {
        return failLiquidateBorrow ? 1 : 0;
    }

    function liquidateBorrowVerify(address, address, address, address, uint, uint) external pure {}

    function seizeAllowed(address, address, address, address, uint) external view returns (uint) {
        return failSeize ? 1 : 0;
    }

    function seizeVerify(address, address, address, address, uint) external pure {}

    function transferAllowed(address, address, address, uint) external view returns (uint) {
        return failTransfer ? 1 : 0;
    }

    function transferVerify(address, address, address, uint) external pure {}
}
