/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iRegisterCircuitVerifierSol from "./IRegisterCircuitVerifier.sol";
export type { iRegisterCircuitVerifierSol };
export type { IDscCircuitVerifier } from "./IDscCircuitVerifier";
export type { IIdentityVerificationHubV2 } from "./IIdentityVerificationHubV2";
export type { IPoseidonT3 } from "./IPoseidonT3";
export type { ISelfVerificationRoot } from "./ISelfVerificationRoot";
